# Data Analytics - Assignment 5 
# Topic: Collaborative Filtering

## Name: NA
## Shailesh Sridhar - 01FB16ECS349
## Shashank Prabhakar - 01FB16ECS356
## Shrey Tiwari - 01FB16ECS368

In [26]:
#Importing Packages
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics.pairwise import cosine_similarity
from scipy.spatial.distance import cosine
import operator
import copy

In [27]:
#Reading datasets
test = pd.read_csv('test.csv')
train = pd.read_csv('train.csv')

### Question 1

In [28]:
#Part a
user_avg = train.groupby('user_id')['rating'].mean().reset_index() 
#reset_index adds column name as rating
user_avg


user_id     rating
0         243   7.000000
1         244   7.000000
2         254   7.000000
3         805   8.000000
4        1075   8.000000
5        1131   7.333333
6        1261   6.000000
7        1424   7.333333
8        1435   9.000000
9        1733   5.000000
10       2197   9.000000
11       2295   6.000000
12       2766   8.000000
13       2977   7.000000
14       3346   9.000000
15       3363  10.000000
16       3373   9.000000
17       3467   9.000000
18       4017   9.000000
19       4571   7.500000
20       4785   9.000000
21       4795   9.000000
22       4938   8.500000
23       5048  10.000000
24       5091   8.000000
25       5439   8.500000
26       5476   4.000000
27       5539   9.500000
28       5582   9.500000
29       5741   8.000000
...       ...        ...
2487   274808   9.000000
2488   275020   9.000000
2489   275210   8.500000
2490   275306  10.000000
2491   275401   5.000000
2492   275571   8.000000
2493   275611   5.000000
2494   275638   6.000000
2495   275677   8.500000
2496   276027   5.000000
2497   276050   8.333333
2498   276165   9.000000
2499   276231   7.000000
2500   276328   7.500000
2501   276681   8.500000
2502   277042   2.000000
2503   277623   6.000000
2504   277639   5.000000
2505   277901   7.333333
2506   277922   9.000000
2507   277923   9.000000
2508   277928   9.000000
2509   277937   8.000000
2510   278026   8.000000
2511   278188   9.000000
2512   278194   9.000000
2513   278356  10.000000
2514   278582   8.500000
2515   278633   8.500000
2516   278854   7.000000

[2517 rows x 2 columns]

In [29]:
#Part b
grouped_items = train.groupby('book')
item_avg = grouped_items['rating'].agg(dict(Average_Rating = np.mean)).reset_index()
item_avg

book  Average_Rating
0                                 1st to Die: A Novel        7.607843
1           A Heartbreaking Work of Staggering Genius        7.488889
2   A Is for Alibi (Kinsey Millhone Mysteries (Pap...        7.560000
3   A Lesson Before Dying (Vintage Contemporaries ...        7.411765
4   A Man Named Dave: A Story of Triumph and Forgi...        7.885714
5   A Walk in the Woods: Rediscovering America on ...        8.531250
6                                   A Wrinkle In Time        8.837838
7                                      Absolute Power        7.800000
8            Ahab's Wife: Or, The Star-Gazer: A Novel        7.656250
9                                       American Gods        7.857143
10                    Angela's Ashes (MMP) : A Memoir        8.102041
11                                Bee Season: A Novel        7.863636
12                                 Bel Canto: A Novel        8.164179
13               Beloved (Plume Contemporary Fiction)        7.942857
14  Big Stone Gap: A Novel (Ballantine Reader's Ci...        7.475000
15                                     Black and Blue        7.606061
16                Cat &amp; Mouse (Alex Cross Novels)        8.370370
17  Chicken Soup for the Soul (Chicken Soup for th...        7.512821
18                            Cold Mountain : A Novel        7.520833
19  Confessions of a Shopaholic (Summer Display Op...        7.790698
20        Confessions of an Ugly Stepsister : A Novel        7.510204
21  Cruel &amp; Unusual (Kay Scarpetta Mysteries (...        8.323529
22  Dance upon the Air (Three Sisters Island Trilogy)        8.119048
23                                         Dead Sleep        7.727273
24                                      Death du Jour        8.093750
25  Don't Sweat the Small Stuff and It's All Small...        7.800000
26                  Drowning Ruth (Oprah's Book Club)        7.476190
27       Face the Fire (Three Sisters Island Trilogy)        8.388889
28                     Fall On Your Knees (Oprah #45)        7.566038
29  Fast Food Nation: The Dark Side of the All-Ame...        8.349206
..                                                ...             ...
70   The Diary of Ellen Rimbauer: My Life at Rose Red        6.833333
71  The Divine Secrets of the Ya-Ya Sisterhood: A ...        7.750000
72                                   The Great Gatsby        7.813333
73  The Hobbit : The Enchanting Prelude to The Lor...        8.760000
74                   The Honk and Holler Opening Soon        8.225000
75                                 The Hours: A Novel        7.765957
76                   The Last Time They Met : A Novel        6.904762
77                          The Lovely Bones: A Novel        8.289683
78                         The Nanny Diaries: A Novel        7.194030
79  The No. 1 Ladies' Detective Agency (Today Show...        8.153846
80                         The Pilot's Wife : A Novel        7.781818
81                      The Poisonwood Bible: A Novel        8.269231
82                The Red Tent (Bestselling Backlist)        8.442857
83                         The Saving Graces: A Novel        7.470588
84                                         The Search        7.558140
85  The Tale of the Body Thief (Vampire Chronicles...        7.145833
86   The Vampire Lestat (Vampire Chronicles, Book II)        8.229730
87  Three To Get Deadly : A Stephanie Plum Novel (...        8.250000
88                                      Tis: A Memoir        7.600000
89  Tribulation Force: The Continuing Drama of Tho...        8.272727
90                                  Two for the Dough        8.434783
91       Vinegar Hill (Oprah's Book Club (Paperback))        6.552632
92                              We Were the Mulvaneys        6.912281
93  Where the Heart Is (Oprah's Book Club (Paperba...        8.204724
94       White Oleander : A Novel (Oprah's Book Club)        8.000000
95  Who Moved My Cheese? An Amazing Way to Deal wi...      

In [17]:
#Part c

#Without using built-in function
true = train.rating
predicted = np.mean(true)
pred = []
avg = np.mean(true)
for i in range(0,len(true)):
    pred.append(avg)
def rmse(true, predicted):
    differences = true - predicted                      
    differences_squared = differences ** 2                    
    mean_of_differences_squared = differences_squared.mean()  
    rmse_val = np.sqrt(mean_of_differences_squared)          
    return rmse_val
rmse_val = rmse(true, predicted)
print("RMS error without built-in function is: " + str(rmse_val))

#Using builtin function
rms = np.sqrt(mean_squared_error(true, pred))
print("RMS error with built-in function is: " + str(rms))

RMS error without built-in function is: 1.78133640702
RMS error with built-in function is: 1.78133640702


In [30]:
#Part d

#Test Matrix
data1 = test
rows = data1.user_id.unique()
cols = data1['book'].unique()
data1 = data1[['user_id', 'book', 'rating']]
idict = dict(zip(cols, range(len(cols))))
udict = dict(zip(rows, range(len(rows))))
data1.user_id = [udict[i] for i in data1.user_id]
data1['book'] = [idict[i] for i in data1['book']]
test_matrix = data1.as_matrix()
print(test_matrix)
#Sparsity of test_matrix
nrow1 = test_matrix.shape[0]
ncol1 = test_matrix.shape[1]
count_zero1 = 0
for i in range(0,nrow1):
    for j in range(0,ncol1):
        if(test_matrix[i][j] == 0):
            count_zero1 = count_zero1 + 1

sparsity_test = count_zero1/(nrow1 * ncol1)
test_sparsity_percentage = sparsity_test*100
print("TEST MATRIX:")
print("There are "+str(count_zero1)+" zero entries out of "+ str(nrow1 * ncol1)+ " total elements")
print("Sparsity Percentage: " + str(test_sparsity_percentage))
    

#Train Matrix
data2 = train
rows = data2.user_id.unique()
cols = data2['book'].unique()
data2 = data2[['user_id', 'book', 'rating']]
idict = dict(zip(cols, range(len(cols))))
udict = dict(zip(rows, range(len(rows))))
data2.user_id = [udict[i] for i in data2.user_id]
data2['book'] = [idict[i] for i in data2['book']]
train_matrix = data2.as_matrix()
print(train_matrix)
#Sparsity of train_matrix
nrow2 = train_matrix.shape[0]
ncol2 = train_matrix.shape[1]
count_zero2 = 0
for k in range(0,nrow2):
    for l in range(0,ncol2):
        if(train_matrix[k][l] == 0):
            count_zero2 = count_zero2 + 1

sparsity_train = count_zero2/(nrow2 * ncol2)
train_sparsity_percentage = sparsity_train*100
print("TRAIN MATRIX:")
print("There are "+str(count_zero2)+" zero entries out of "+ str(nrow2 * ncol2)+ " total elements")
print("Sparsity Percentage: " + str(train_sparsity_percentage))

[[  0   0   7]
 [  1   1   8]
 [  2   2   8]
 ..., 
 [846  51  10]
 [847  28   9]
 [419  46  10]]
TEST MATRIX:
There are 24 zero entries out of 3666 total elements
Sparsity Percentage: 0.6546644844517185
[[   0    0    5]
 [   1    1    9]
 [   2    2    6]
 ..., 
 [ 635   73   10]
 [ 283   41    8]
 [2516   78    7]]
TRAIN MATRIX:
There are 254 zero entries out of 16098 total elements
Sparsity Percentage: 1.5778357559945337


In [31]:
#Part e
def predict_naive(user, item):
    prediction = imean1[item] + umean1[user] - amean1
    return prediction
naive = np.zeros((len(rows),len(cols)))
for row in train_matrix:
    naive[row[0], row[1]] = row[2]

amean1 = np.mean(naive[naive!=0])
nnaiverows = naive.shape[0]
nnaivecols = naive.shape[1]

naive = np.zeros((len(rows),len(cols)))
for row in train_matrix:
    naive[row[0], row[1]] = row[2]
amean1 = np.mean(naive[naive!=0])
umean1 = sum(naive.T) / sum((naive!=0).T)
imean1 = sum(naive) / sum((naive!=0))          
            
predictions = []
targets = []
for row in test_matrix:
    user, item, actual = row[0], row[1], row[2]
    predictions.append(predict_naive(user, item))
    targets.append(actual)
targets = np.array(targets)
predictions = np.array(predictions)
print("RMS Error: ",rmse(targets,predictions)) 



RMS Error:  2.28475661194


### Question 2

In [32]:
#Part a

def cos(mat, a, b):
    if a == b:
        return 1
    aval = mat.T[a].nonzero()
    bval = mat.T[b].nonzero()
    corated = np.intersect1d(aval, bval)
    if len(corated) == 0:
        return 0
    avec = np.take(mat.T[a], corated)
    bvec = np.take(mat.T[b], corated)
    val = 1 - cosine(avec, bvec)
    if np.isnan(val):
        return 0
    return val

def pr(mat, a, b, imean):
    if a == b:
        return 1
    aval = mat.T[a].nonzero()
    bval = mat.T[b].nonzero()
    corated = np.intersect1d(aval, bval)
    if len(corated) < 2:
        return 0
    avec = np.take(mat.T[a], corated)
    bvec = np.take(mat.T[b], corated)
    avec1 = avec - imean[a]
    bvec1 = bvec - imean[b]
    val = 1 - cosine(avec1, bvec1)
    if np.isnan(val):
        return 0
    return val

def itemsimilar(mat, option):
    # *Calculate amean, umean and imean as before
    amean = np.mean(mat[mat!=0])
    nmatrows = mat.shape[0]
    nmatcols = mat.shape[1]
    imean = [0 for i in range(nmatcols)]
    umean = [0 for i in range(nmatrows)]
    
    
    for i in range(nmatcols):
        imean[i] = sum(mat.T[i]) / sum((mat.T[i]!=0))          
    for j in range(nmatrows):
        umean[j] = sum(mat[j]) / sum((mat[j]!=0))
   
    n = mat.shape[1]
    # *initialize a zero matrix with dimensions n,n to get the similarity matrix
    sim_mat = np.zeros((n,n))
    if option == 'pr':
    #print("PR")
        for i in range(n):
            for j in range(n):
                sim_mat[i][j] = pr(mat, i, j, imean)
        sim_mat = (sim_mat + 1)/2
    elif option == 'cos':
    #print("COS")
        for i in range(n):
            for j in range(n):
                sim_mat[i][j] = cos(mat, i, j)
    else:
    #print("Default")
        sim_mat = cosine_similarity(mat.T)
    return sim_mat, amean, umean, imean



def kMostSimilar(sim_mat,x,k):
    global udict
    reverse_dict = sorted(udict.items(),  key=operator.itemgetter(1))
    N = k
    a = copy.deepcopy(sim_mat)
    user_vals = a[udict[x]]
    idx_1d = user_vals.argsort()[-N:]
    for i in idx_1d:
        print(user_vals[i],i,reverse_dict[i][0])


rows = data1.user_id.unique()
cols = data1['book'].unique()
mat = np.zeros((len(rows),len(cols)))
for row in test_matrix:
    mat[row[0], row[1]] = row[2]
cosine_similarity_mat,amean_cos,umean_cos,imean_cos = itemsimilar(mat.T,'cos')
pearson_similarity_mat,amean_pearson,umean_pearson,imean_pearson = itemsimilar(mat.T,'pr')


In [33]:
#Part b                   
def predict(user, item, mat, item_similarity, amean, umean, imean,
k=20):
    nzero = mat[user].nonzero()[0]
    if len(nzero) == 0:
        return amean
    baseline = imean + umean[user] - amean
    choice = nzero[item_similarity[item, nzero].argsort()[::-1][:k]]
    prediction = ((mat[user, choice] - baseline[choice]).dot(item_similarity[item,
    choice])/ sum(item_similarity[item, choice])) + baseline[item]
    if np.isnan(prediction):
        prediction = amean
    if prediction > 10:
        prediction = 10
    if prediction < 1:
        prediction = 1
    return prediction


In [34]:
#Part c

def get_results(train_data, test_data,option, rows, cols, k):
# *initialize a zero matrix called full_mat with dim(rows,cols)
    full_mat = np.zeros((rows,cols))
    for row in train_data:
        full_mat[row[0], row[1]] = row[2]
    item_similarity, amean, umean, imean = itemsimilar(full_mat, option)
    preds = []
    real = []
    for row in train_data:
        preds.append(predict(row[0],row[1],full_mat,item_similarity,amean,umean,imean))
        real.append(row[2])
    # *initialize empty preds and real lists.
    # *For each row in train_data, call the predict function using the above
    #values as parameters, as explained before for the naïve prediction. Keep updating
    #the preds and real lists.
    # *Calculate the RMSE error of both lists.
    err1 = rmse(np.array(preds),np.array(real))
    print('Train Error')
    print('RMSE : %.4f' % err1)
    preds = []
    real = []
    for row in test_data:
        preds.append(predict(row[0],row[1],full_mat,item_similarity,amean,umean,imean))
        real.append(row[2])
    # *Reinitialize the preds and real lists to empty lists
    # *For each row in the test_data, call the predict function using the above
    #values as parameters, as explained before for the naïve prediction. Keep updating
    #the preds and real lists.
    # *Calculate the RMSE error of both lists.\
    err2 = rmse(np.array(preds),np.array(real))
    print('Test Error')
    print('RMSE : %.4f' % err2)
get_results(train_matrix,test_matrix,'pr',nnaiverows,nnaivecols,1)

Train Error
RMSE : 0.7308
Test Error
RMSE : 2.2465


In [ ]:
#Part d
'''The value of k is non-parametric and a general rule of thumb in choosing the value of k is k = sqrt(N)/2, 
where N stands for the number of samples in your training dataset.A small value of k means that noise will have a higher influence
on the result and a large value make it computationally expensive. Generally, it is suggested that we try and keep
the value of k odd(in the case of two classes), so that there is no tie between choosing a class. Similarly, 
in case of 'c' classes, we would avoid choosing k as a multiple of 'c'.

A small value of k means that noise will have a higher influence on the result and a large value make it computationally expensive.
The class boundaries become smoother with an increase in the value of K.

At K=1, we were overfitting the boundaries. Hence, error rate initially decreases and reaches a minima. 
After the minima point, it then increases with increasing K. To get the optimal value of K, you can segregate the
training and validation from the initial dataset. Now plot the validation error curve to get the optimal value of K. 
This value of K should be used for all predictions.'''